window.eyedrawDoodleTitles = {
	"Sketch" : "Freehand sketch",
    "ROPDemarcationLine": "Demarcation line",
    "ROPRidge": "Elevated ridge",
    "ROPstage3": "Fibrovascular proliferation",
    "ROPRD": "Retinal detachment",
    "ROPRRD": "Total retinal detachment",
    "HardExudate": "Exudate",
    "UTear": "Traction \u2018U\u2019 tear",
    "SubretinalFluid": "Subretinal fluid",
    "MaculaMark": "Macula",
    "SupTempArcade": "Superotemporal arcade",
    "SupNasalArcade": "Superonasal arcade",
    "InfNasalArcade": "Inferonasal arcade",
    "InfTempArcade": "Inferotemporal arcade",
    "SubretinalFluid" : "Subretinal Fluid",
    "LaserDevel" : "Laser",
    "ROPHaemorrhage": "Retinal Haemorrhage",
//     "VitreousHaze": "Vitreous Haze",
};